/** account **/
export const LOGIN = 'LOGIN';
export const LOGIN_QR = 'LOGIN_QR';
export const LOGOUT = 'LOGOUT';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

/** file-resource ***/
export const UPLOAD_BASE64 = 'UPLOAD_BASE64';

/** agent-assignment-controller  **/
export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const CUSTOMER_ASSIGN = 'CUSTOMER_ASSIGN';
export const AGENT_HISTORY = 'AGENT_HISTORY';
export const AGENT_CORE_USER = 'AGENT_CORE_USER';
export const CUSTOMER_ACTIVE = 'CUSTOMER_ACTIVE';
export const CUSTOMER_ACTIVE_EVENT = 'CUSTOMER_ACTIVE_EVENT';
export const USER_REFERRAL = 'USER_REFERRAL';

/** agent-assistant-controller **/
export const ANGENT_ASSISTANT_LIST = 'ANGENT_ASSISTANT_LIST';

/** agent-controller **/
export const AGENT_LIST = 'AGENT_LIST';
export const AGENT_SCHEDULING_LIST = 'AGENT_SCHEDULING_LIST';
export const AGENT_ACCOUNT = 'AGENT_ACCOUNT';
export const AGENT_ENABLE = 'AGENT_ENABLE';

export const AGENT_SUPERVISOR = 'AGENT_SUPERVISOR';
export const AGENT_TEAM = 'AGENT_TEAM';
export const AGENT_TEAM_ADD = 'AGENT_TEAM_ADD';
export const AGENT_TEAM_CHANGE = 'AGENT_TEAM_CHANGE';
export const AGENT_TEAM_EDIT = 'AGENT_TEAM_EDIT';
export const AGENT_TEAM_DELETE = 'AGENT_TEAM_DELETE';
export const AGENT_TEAM_XZJ_LIST = 'AGENT_TEAM_XZJ_LIST';
export const AGENT_SUPERVISOR_CANDIDATES = 'AGENT_SUPERVISOR_CANDIDATES';

/** app-dial-controller **/
export const APP_CALL = 'APP_CALL';
export const APP_CALL_STATUS = 'APP_CALL_STATUS';

/** agent-profile-controller **/
export const AGENT_PROFILE_HEADER = 'AGENT_PROFILE_HEADER';
export const AGENT_PROFILE = 'AGENT_PROFILE';
export const AGENT_ID_INFO = 'AGENT_ID_INFO';
export const EDIT_AGENT_PROFILE = 'EDIT_AGENT_PROFILE';
export const AGENT_PROFILE_ADD_ROLES = 'AGENT_PROFILE_ADD_ROLES';
export const AGENT_PROFILE_ROLES = 'AGENT_PROFILE_ROLES';

/** agent-reward-controller **/ 
export const AGENT_REWARD = 'AGENT_REWARD';
export const AGENT_REWARD_SUMMARY = 'AGENT_REWARD_SUMMARY';
export const AGENT_REWARD_EXPORT = 'AGENT_REWARD_EXPORT';

/** agent-sign-in-controller **/
export const AGENT_SIGN_IN = 'AGENT_SIGN_IN';
export const AGENT_SIGN_IN_LIST = 'AGENT_SIGN_IN_LIST';
export const AGENT_SIGN_IN_LIST_EXPORT = 'AGENT_SIGN_IN_LIST_EXPORT';

/** agent-task-controller **/
export const AGENT_TASK_LIST = 'AGENT_TASK_LIST';
export const AGENT_TASK_COMPLETE = 'AGENT_TASK_COMPLETE';
export const AGENT_TASK_TYPE = 'AGENT_TASK_TYPE';
export const AGENT_SIGN_UP_TASK = 'AGENT_SIGN_UP_TASK';
export const AGENT_TASK_CLAIM = 'AGENT_TASK_CLAIM';

/** application-controller **/
export const CANCEL_APPLY = 'CANCEL_APPLY';
export const POSITION_HANDLE = 'POSITION_HANDLE';
export const CANCEL_RESERVE_POSITION = 'CANCEL_RESERVE_POSITION';
export const CANCEL_PICK_UP = 'CANCEL_PICK_UP';
export const RESERVE_NOTIFICATION = 'RESERVE_NOTIFICATION';
export const DELAY_TASK = 'DELAY_TASK';

/** reservation-controller **/
export const RESERVE = 'RESERVE';
export const RESERVE_PICKUP_LOCATION = 'RESERVE_PICKUP_LOCATION';
export const RESERVE_PICKUP_DATE = 'RESERVE_PICKUP_DATE';
export const RESERVE_PICKUP_ALL = 'RESERVE_PICKUP_ALL';
export const RESERVE_TOLL = 'RESERVE_TOLL';

/** customer-comment-controller **/
export const RECORD_ADD = 'RECORD_ADD';
export const RECORD_HISTORY = 'RECORD_HISTORY';

/** customer-controller **/
export const CUSTOMER_INFO = 'CUSTOMER_INFO';
export const POSITION_APPLY_LIST = 'POSITION_APPLY_LIST';
export const APPLY_RECORD_LIST = 'APPLY_RECORD_LIST';
export const RESERVE_LIST = 'RESERVE_LIST';
export const PICKUP_LIST = 'PICKUP_LIST';
export const SIGNIN_LIST = 'SIGNIN_LIST';
export const ONBOARDING_LIST = 'ONBOARDING_LIST';
export const RETURN_FEE_LIST = 'RETURN_FEE_LIST';
export const SOURCE_LIST = 'SOURCE_LIST';
export const CUSTOMER_REFERRAL_LIST = 'CUSTOMER_REFERRAL_LIST';
export const CUSTOMER_REFERRAL = 'CUSTOMER_REFERRAL';
export const CUSTOMER_REMARK = 'CUSTOMER_REMARK';
export const CUSTOMER_REMARK_DETAIL = 'CUSTOMER_REMARK_DETAIL';
export const CUSTOMER_FOLLOWING = 'CUSTOMER_FOLLOWING';
export const POSITION_APPLIED = 'POSITION_APPLIED';
export const CUSTOMER_ID = 'CUSTOMER_ID';
export const CUSTOMER_SPRING_RESERVE = 'CUSTOMER_SPRING_RESERVE';
export const CUSTOMER_SPRING_TRIP = 'CUSTOMER_SPRING_TRIP';
export const WORK_CRAD = 'WORK_CRAD';
export const CUSTOMER_AUTH_NAME = 'CUSTOMER_AUTH_NAME';

/** enterprise-controller **/
export const ENTERPRISE_CITY = 'ENTERPRISE_CITY';
export const ENTERPRISE_POSITION = 'ENTERPRISE_POSITION';

/** position-controller **/
export const POSITION_LIST = 'POSITION_LIST';
export const POSITION_CITY = 'POSITION_CITY';
export const POSITION_DETAIL = 'POSITION_DETAIL';
export const INTERVIEW_DATE = 'INTERVIEW_DATE';
export const POSITION_WELFARE = 'POSITION_WELFARE';
export const POSITION_FEATURE = 'POSITION_FEATURE';

/** store-controller **/
export const STORE_LIST = 'STORE_LIST';
export const STORE_LOCATION_LIST = 'STORE_LOCATION_LIST';

/** summary-controller **/
export const SUMMARY_AGENT = 'SUMMARY_AGENT';
export const SUMMARY_ASSIGNMENTS = 'SUMMARY_ASSIGNMENTS';
export const SUMMARY_DASHBOARD = 'SUMMARY_DASHBOARD';
export const SUMMARY_AGENT_EXPORT = 'SUMMARY_AGENT_EXPORT';
export const SUMMARY_NEW_SIGN_UP = 'SUMMARY_NEW_SIGN_UP';
export const SUMMARY_BOARD_DETAIL = 'SUMMARY_BOARD_DETAIL';
export const CONTACT_RATE = 'CONTACT_RATE';
export const SUMMARY_RESERVATION = 'SUMMARY_RESERVATION';
export const SUMMARY_WORK_TRACK = 'SUMMARY_WORK_TRACK';
export const SUMMARY_WORK_TRACK_EXPORT = 'SUMMARY_WORK_TRACK_EXPORT';
export const AGENT_CONVERSION_INDEX = 'AGENT_CONVERSION_INDEX';
export const SUMMARY_SIGN_IN_PROGRESS = 'SUMMARY_SIGN_IN_PROGRESS';
export const SUMMARY_SIGN_IN_PROGRESS_MONTH = 'SUMMARY_SIGN_IN_PROGRESS_MONTH';
export const SUMMARY_WX_INDEX = 'SUMMARY_WX_INDEX';
export const SUMMARY_LEADER_BOARD = 'SUMMARY_LEADER_BOARD';
export const SUMMARY_LEADER_BOARD_SIGN = 'SUMMARY_LEADER_BOARD_SIGN';
export const SUMMARY_LEADER_BOARD_INVITE = 'SUMMARY_LEADER_BOARD_INVITE';
export const SUMMARY_SIGN_IN_TREND = 'SUMMARY_SIGN_IN_TREND';


/** weekly-salary-controller **/
export const SALARY_SIGN_IN = 'SALARY_SIGN_IN';
export const SALARY_SIGN_IN_LIST = 'SALARY_SIGN_IN_LIST';
export const SALARY_PAYMENT_LIST = 'SALARY_PAYMENT_LIST';
export const SALARY_DAY_LIST = 'SALARY_DAY_LIST';

/** work-region-controller **/
export const REGIONS = 'REGIONS';
export const REGIONS_CITY = 'REGIONS_CITY';
export const REGIONS_ASSIGNED_AGENTS = 'REGIONS_ASSIGNED_AGENTS';
export const REGIONS_ASSIGNMENT = 'REGIONS_ASSIGNMENT';

/** work-scheduling-controller **/
export const WORK_SCHEDULING_LIST = 'WORK_SCHEDULING_LIST';
export const WORK_SCHEDULING_ADD = 'WORK_SCHEDULING_ADD';
export const WORK_SCHEDULING_EDIT = 'WORK_SCHEDULING_EDIT';
export const WORK_SCHEDULING_DATE = 'WORK_SCHEDULING_DATE';

/** assign-rule-configure-controller*/
export const ASSIGN_RULE_CONFIGURE_LIST = 'ASSIGN_RULE_CONFIGURE_LIST';
export const ASSIGN_RULE_CONFIGURE = 'ASSIGN_RULE_CONFIGURE';
export const ALL_ASSIGN_RULE_CONFIGURE_LIST = 'ALL_ASSIGN_RULE_CONFIGURE_LIST' ;
export const ALL_ASSIGN_RULE_CONFIGURE_EDIT = 'ALL_ASSIGN_RULE_CONFIGURE_EDIT' ;

/** call-center-controller  **/
export const CALL = 'CALL';
export const CALL_RECORD = 'CALL_RECORD';
export const CALL_SEAT = 'CALL_SEAT';
export const CALL_SIP_PHONE = 'CALL_SIP_PHONE';
export const CALL_ADD = 'CALL_ADD';
export const CALL_DELETE = 'CALL_DELETE';
export const CALL_UNBIND = 'CALL_UNBIND';
export const CALL_BIND_EDIT = 'CALL_BIND_EDIT';
export const CALL_WAY_SWITCH = 'CALL_WAY_SWITCH';
export const CALL_WAY_LIST = 'CALL_WAY_LIST';
export const CALL_IS_TEL = 'CALL_IS_TEL';

/** return-visit  **/
export const UNCLAIMED_LIST = 'UNCLAIMED_LIST';
export const CLAIMED_LIST = 'CLAIMED_LIST';
export const NOTICES = 'NOTICES';
export const CLAIM_SUCCESS = 'CLAIM_SUCCESS';
export const LOCATION_OF_EXPECTATION = 'LOCATION_OF_EXPECTATION';
export const REMARK_COMMENT = 'REMARK_COMMENT';
export const REMARK_COMMENTS = 'REMARK_COMMENTS';
export const REMARK_USER = 'REMARK_USER';
export const REMARK_USERS = 'REMARK_USERS';
export const COMPLETELIST = 'COMPLETELIST';
export const CUSTOMERS_ALLOCATION = 'CUSTOMERS_ALLOCATION';

/** we-chat-account-controller **/
export const WECHAT = 'WECHAT';
export const WECHAT_ADD = 'WECHAT_ADD';
export const WECHAT_EDIT = 'WECHAT_EDIT';
export const WECHAT_DELETE = 'WECHAT_DELETE';

/** service-follow-up-controller **/
export const EVENT_RECEPTIONIST = 'EVENT_RECEPTIONIST';
export const EVENT_REGIST = 'EVENT_REGIST';

export const ENTRYIN_LIST = 'ENTRYIN_LIST';
export const ENTRYIN_LIST_CLAIM = 'ENTRYIN_LIST_CLAIM';
export const ENTRYIN_LIST_COMPLETE = 'ENTRYIN_LIST_COMPLETE';

export const ENTRYIN_CLAIM = 'ENTRYIN_CLAIM';
export const ENTRYIN_VISIT = 'ENTRYIN_VISIT';
export const ENTRYIN_VISIT_RECORDS = 'ENTRYIN_VISIT_RECORDS';
export const ENTRYIN_HISTORY_RECORDS = 'ENTRYIN_HISTORY_RECORDS';
export const ENTRYIN_STATISTICS = 'ENTRYIN_STATISTICS';

/** service-event-controller **/
export const EVENT_CUSTOMER_LIST = 'EVENT_CUSTOMER_LIST';
export const EVENT_CUSTOMER = 'EVENT_CUSTOMER';
export const EVENT_CUSTOMER_EXPORT = 'EVENT_CUSTOMER_EXPORT';

/**source-configure-controller**/
export const SOURCE_CONFIGURE = 'SOURCE_CONFIGURE';
export const SOURCE_CONFIGURE_ADD = 'SOURCE_CONFIGURE_ADD';
export const SOURCE_CONFIGURE_EDIT = 'SOURCE_CONFIGURE_EDIT';
export const SOURCE_CONFIGURE_DELETE = 'SOURCE_CONFIGURE_DELETE';
export const SOURCE_CONFIGURE_AREA = 'SOURCE_CONFIGURE_AREA';
export const SOURCE_CONFIGURE_AREA_ADD = 'SOURCE_CONFIGURE_AREA_ADD';
export const SOURCE_CONFIGURE_AREA_DELTET = 'SOURCE_CONFIGURE_AREA_DELTET';

